const NoteConstants = {
  NOTES_RECEIVED: "NOTES_RECEIVED",
  NOTE_RECEIVED: "NOTE_RECEIVED",
  NOTE_REMOVED: "NOTE_REMOVED",
  NOTES_BY_NOTEBOOK_RECEIVED: "NOTES_BY_NOTEBOOK_RECEIVED"
};

module.exports = NoteConstants;
